### ISSUE TITLE
Action Names only appear in Japanese

### ISSUE THREAD

**Issue by Griever92** [anoyetta/ACT.UltraScouter#2]
Casting/Action bars currently display the action name in Japanese, no English option appears to be available.

**Comment by anoyetta** [comment]
Action.csv of EN, FR, DE was added.
https://github.com/anoyetta/ACT.UltraScouter/releases/tag/v0.10.2

1. rename "resources\xivdb\Action.csv" -> "resources\xivdb\Action.csv_ja.csv"
2. rename "resources\xivdb\Action_en.csv" -> "resources\xivdb\Action.csv.csv"
3. reboot ACT.exe
Action Name should change to English.
