### ISSUE TITLE
ULTRA SCOUTER initPlug error

### ISSUE THREAD

**Issue by hforem** [anoyetta/ACT.UltraScouter#6]
few days ago when i upload my Hojoring to 5.3.1, my ULTRA SCOUTER crashed cause an error and i couldnt use the plugin in. Here is the image about what happened. Any idea about how to fix it x.x really like ULTRA SCOUTER!
![5 xdj0lyzp5p 5mv19ia fi](https://user-images.githubusercontent.com/37395823/37448137-42376668-27e2-11e8-95b1-115bcbed2fa1.png)
![1v1 ke ya sphnq6 g40r6](https://user-images.githubusercontent.com/37395823/37448140-4359e606-27e2-11e8-84db-80072e58ad16.png)
i dont know hoe to translate the error to JP. Its something like "there's an error in System.InvalidOperationException:XML (1,1) because the character is invalid in the image 1;
the 2nd images of DelnitPlugin error says that the System.NullRefrenceException do not work on the 2 ultrascouter files blow.

**Comment by anoyetta** [comment]
Chinese?
I cant understand Chinese.

XMLパースエラーのようにみえる。設定ファイルが破損しているのではないでしょうか？
%APPDATA%\anoyetta\ACT\ACT.UltraScounter.config 
を削除してから起動してください。

**Comment by hforem** [comment]
削除した後動いたです！日本語は苦手ですのでごめんなさい、返事ありがとうございました！
